import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Inter , Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={outfit.className}>
        <Navbar/>
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
